kind: pipeline
name: default

# Limits how many of these builds can run on the drone runner at a time, this isn't about cores
concurrency:
  limit: 1

volumes:
  - name: cache
    host:
      path: /home/go/pkg

steps:
  - name: spire-build-release
    image: akkadius/spire:go-workspace
    environment:
      GH_RELEASE_GITHUB_API_TOKEN:
        from_secret: GH_RELEASE_GITHUB_API_TOKEN
    commands:
      - sudo chown -R go /drone/src
      - ./scripts/build-release.sh
    when:
      branch: [ "master" ]
      event: [ push ]
    volumes:
      - name: cache
        path: /home/go/pkg
