version: '2.4'

networks:
  backend:
    driver: bridge

volumes:
  shared-pkg:
  build-cache:

services:
  workspace:
    restart: unless-stopped
    image: prod
    build:
      context: ./containers/prod
    hostname: prod
    tty: true
    volumes:
      - ./:/home/go/src
      - build-cache:/home/go/.cache/
      - shared-pkg:/home/go/pkg
    environment:
      TZ: America/Chicago
      CGO_ENABLED: 0
      APP_ENV: production
      IS_HOSTED_READ_ONLY_MODE: 1
      TERM: xterm-256color
    ports:
      - ${IP_ADDRESS:-0.0.0.0}:80:3010
    networks:
      - backend
    command: "air -c .air.prod.toml"
