version: '2.4'

networks:
  backend:
    driver: bridge

volumes:
  shared-pkg:
  build-cache:

services:

  #############################################
  # workspace
  #############################################
  workspace:
    image: go-workspace
    build:
      context: ./containers/workspace
    hostname: go-workspace
    tty: true
    volumes:
      - ./:/home/go/src:delegated
      - build-cache:/home/go/.cache/
      - shared-pkg:/home/go/pkg
    environment:
      TZ: America/Chicago
      CGO_ENABLED: 0
      APP_ENV: local
      TERM: xterm-256color
    ports:
      - ${IP_ADDRESS:-0.0.0.0}:3000:3000
      - ${IP_ADDRESS:-0.0.0.0}:3001:3001
    networks:
      - backend
    command: "/bin/bash -c 'sudo chown go -R /home/go/pkg && go get || true && bash'"

  #############################################
  # prod
  #############################################
  prod:
    restart: unless-stopped
    image: prod
    build:
      context: ./containers/prod
    hostname: prod
    tty: true
    volumes:
      - ./:/home/go/src
      - build-cache:/home/go/.cache/
      - shared-pkg:/home/go/pkg
    environment:
      TZ: America/Chicago
      CGO_ENABLED: 0
      APP_ENV: production
      TERM: xterm-256color
    ports:
      - ${IP_ADDRESS:-0.0.0.0}:80:80
      - ${IP_ADDRESS:-0.0.0.0}:3001:3001
    networks:
      - backend
    command: "air -c .air.prod.toml"

  #############################################
  # mysql
  #############################################

  mysql:
    restart: unless-stopped
    build:
      context: ./containers/mariadb
      args:
        - INNODB_BUFFER_POOL_SIZE=${INNODB_BUFFER_POOL_SIZE:-512MB}
    ports:
      - ${IP_ADDRESS:-0.0.0.0}:3306:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql:delegated
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=NO
      - TZ=${TZ:-US/Central}
    networks:
      - backend

  #############################################
  # redis
  #############################################

  redis:
    image: redis:latest
    expose:
      - 6379
    networks:
      - backend

  #############################################
  # jaeger tracing
  #############################################

  jaeger:
    image: jaegertracing/all-in-one:1.18
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - backend
